// Code generated by MockGen. DO NOT EDIT.
// Source: repository/indexSavingRepository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	repository "go_practice/repository"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIIndexSavingRepository is a mock of IIndexSavingRepository interface.
type MockIIndexSavingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIIndexSavingRepositoryMockRecorder
}

// MockIIndexSavingRepositoryMockRecorder is the mock recorder for MockIIndexSavingRepository.
type MockIIndexSavingRepositoryMockRecorder struct {
	mock *MockIIndexSavingRepository
}

// NewMockIIndexSavingRepository creates a new mock instance.
func NewMockIIndexSavingRepository(ctrl *gomock.Controller) *MockIIndexSavingRepository {
	mock := &MockIIndexSavingRepository{ctrl: ctrl}
	mock.recorder = &MockIIndexSavingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIndexSavingRepository) EXPECT() *MockIIndexSavingRepositoryMockRecorder {
	return m.recorder
}

// GetPersons mocks base method.
func (m *MockIIndexSavingRepository) GetPersons() ([]repository.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersons")
	ret0, _ := ret[0].([]repository.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersons indicates an expected call of GetPersons.
func (mr *MockIIndexSavingRepositoryMockRecorder) GetPersons() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersons", reflect.TypeOf((*MockIIndexSavingRepository)(nil).GetPersons))
}
